version: '2'
services:
  voyant:
    image: 725535576166.dkr.ecr.us-east-1.amazonaws.com/voyant-example:latest
    #image: voyant:latest
    #build: voyant-local
    container_name: voyant
    ports:
      - "8080:8080"
    volumes:
       - ./data:/usr/local/tomcat/temp
    #environment:
    #    CATALINA_OPTS: -Dorg.voyanttools.server.allowinput=false 
    #    CATALINA_OPTS: -Dorg.voyanttools.server.allowinput=false -Dorg.voyanttools.voyant.openmenu=shakespeare:ShakespearePlays

# volumes:
#   data:
  
